#!/usr/bin/env bash
source "$(cd -- "$(dirname -- "$0")" && pwd)/_common.sh"
preflight; confirm "crear o actualizar Lambdas y HTTP API de Blog"
ACCOUNT_ID="$(account_id)"; REGISTRY="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"; FANOUT_URL="$(aws_cmd sqs get-queue-url --queue-name fanout-jobs --query QueueUrl --output text)"; NOTIFICATION_URL="$(aws_cmd sqs get-queue-url --queue-name notification-jobs --query QueueUrl --output text)"
deploy() { local name="$1" repository="$2" role="$3" variables="$4" image="$REGISTRY/$2:$IMAGE_TAG" role_arn="arn:aws:iam::$ACCOUNT_ID:role/$role"; if aws_cmd lambda get-function --function-name "$name" >/dev/null 2>&1; then aws_cmd lambda update-function-code --function-name "$name" --image-uri "$image" >/dev/null; aws_cmd lambda wait function-updated --function-name "$name"; aws_cmd lambda update-function-configuration --function-name "$name" --environment "Variables=$variables" --timeout 30 --memory-size 256 --architectures arm64 >/dev/null; else aws_cmd lambda create-function --function-name "$name" --package-type Image --code "ImageUri=$image" --role "$role_arn" --architectures arm64 --timeout 30 --memory-size 256 --environment "Variables=$variables" >/dev/null; fi; }
deploy blog-create-post blog-create-post blog-create-post-role '{TABLENAME=author_post}'
deploy blog-get-posts blog-get-posts blog-get-posts-role '{TABLENAME=author_post}'
deploy blog-fanout-starter blog-fanout-starter blog-fanout-starter-role "{FANOUT_PROGRESS_TABLE=$PROGRESS_TABLE,FANOUT_JOBS_QUEUE_URL=$FANOUT_URL}"
deploy blog-follower-worker blog-follower-worker blog-follower-worker-role "{FOLLOWERS_TABLE=$POSTS_TABLE,FANOUT_PROGRESS_TABLE=$PROGRESS_TABLE,FANOUT_JOBS_QUEUE_URL=$FANOUT_URL,NOTIFICATION_JOBS_QUEUE_URL=$NOTIFICATION_URL}"
API_ID="$(aws_cmd apigatewayv2 get-apis --query "Items[?Name=='$API_NAME'].ApiId | [0]" --output text)"; [[ "$API_ID" != None && -n "$API_ID" ]] || API_ID="$(aws_cmd apigatewayv2 create-api --name "$API_NAME" --protocol-type HTTP --query ApiId --output text)"
route() { local key="$1" function="$2" arn integration; [[ "$(aws_cmd apigatewayv2 get-routes --api-id "$API_ID" --query "Items[?RouteKey=='$key'].RouteId | [0]" --output text)" != None ]] && return; arn="$(aws_cmd lambda get-function --function-name "$function" --query 'Configuration.FunctionArn' --output text)"; integration="$(aws_cmd apigatewayv2 create-integration --api-id "$API_ID" --integration-type AWS_PROXY --integration-uri "arn:aws:apigateway:$AWS_REGION:lambda:path/2015-03-31/functions/$arn/invocations" --payload-format-version 2.0 --query IntegrationId --output text)"; aws_cmd apigatewayv2 create-route --api-id "$API_ID" --route-key "$key" --target "integrations/$integration" >/dev/null; aws_cmd lambda add-permission --function-name "$function" --statement-id "apigw-$API_ID-$function" --action lambda:InvokeFunction --principal apigateway.amazonaws.com --source-arn "arn:aws:execute-api:$AWS_REGION:$ACCOUNT_ID:$API_ID/*/*" >/dev/null 2>&1 || true; }
route 'POST /authors/{authorId}/posts' blog-create-post; route 'GET /authors/{authorId}/posts' blog-get-posts; route 'GET /authors/{authorId}/drafts' blog-get-posts
echo "API: $(aws_cmd apigatewayv2 get-api --api-id "$API_ID" --query ApiEndpoint --output text)"
echo "No se crean event source mappings todavía: la transición DRAFT -> PUBLISHED sigue pendiente."
